### ISSUE TITLE
hook 程序选择之后无法确定

### ISSUE THREAD

**Issue by sunlifeng** [littleRich/VirtualLocation#4]
进入hook 之后程序选择了，返回之后回到程序选择还是没有选择状态。 
测试钉钉等软件都这样。

**Comment by sunlifeng** [comment]
詳細看了程序代碼，發現hook幾個固定程序。選擇之類是沒用的。 closed

**Comment by littleRich** [comment]
钉钉没在可视化界面上操作的，因为涉及到公司打卡问题没敢乱加，所以有需要虚拟打卡的可以在代码里直接修改公司经纬度就可以，在那个有高德经纬度类文件里该就行。

**Comment by sunlifeng** [comment]
修改了公司经纬度解决了。ok thanks
