### ISSUE TITLE
安卓模拟器测试

### ISSUE THREAD

**Issue by imtypist** [littleRich/VirtualLocation#5]
不知道作者有没有在安卓模拟器上测试过，我尝试在安卓模拟器上hook修改高德地图，百度地图这一类地图的坐标，没有起作用，不知道是不是受安卓模拟器本身自带虚拟定位功能的影响，这种情况你遇到过吗？
ps 我用的是夜神模拟器
谢谢！

**Comment by v515527946** [comment]
Android模拟器自身的定位有问题的，拿真机测吧
